const header=document.querySelector(".header"),menuButton=document.querySelector(".menu-toggle"),nav=document.querySelector(".navbar"),search=document.querySelector("#search-input"),feedback=document.querySelector("#search-feedback"),cards=[...document.querySelectorAll(".product-card")],lightbox=document.querySelector("#lightbox"),lightboxImage=document.querySelector("#lightbox-img");
addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>20),{passive:true});
menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");document.body.classList.toggle("menu-open",open);menuButton.setAttribute("aria-expanded",open)});
nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{nav.classList.remove("open");document.body.classList.remove("menu-open");menuButton.setAttribute("aria-expanded","false")}));
search.addEventListener("input",()=>{const term=search.value.trim().toLocaleLowerCase("pt-BR");let total=0;cards.forEach(card=>{const match=card.dataset.modelo.toLocaleLowerCase("pt-BR").includes(term)||card.textContent.toLocaleLowerCase("pt-BR").includes(term);card.classList.toggle("hidden",!match);if(match)total++});feedback.textContent=term?(total?`${total} ${total===1?"modelo encontrado":"modelos encontrados"}.`:"Nenhum modelo encontrado. Fale conosco para consultar outras opções."):"";feedback.classList.toggle("active",!!term)});
document.querySelectorAll(".product-image").forEach(button=>button.addEventListener("click",()=>{const image=button.querySelector("img");lightboxImage.src=image.src;lightboxImage.alt=image.alt;lightbox.classList.add("show");lightbox.setAttribute("aria-hidden","false")}));
function closeLightbox(){lightbox.classList.remove("show");lightbox.setAttribute("aria-hidden","true");lightboxImage.src=""}
document.querySelector(".close").addEventListener("click",closeLightbox);lightbox.addEventListener("click",event=>{if(event.target===lightbox)closeLightbox()});addEventListener("keydown",event=>{if(event.key==="Escape")closeLightbox()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(element=>observer.observe(element));
